### ISSUE TITLE
Commit disaster

### ISSUE THREAD

**Issue by kot2002** [roxas75/rxTools#268]
All commits have been doubled.

**Comment by hg8** [comment]
How is that possible ?

**Comment by AlbertoSONIC** [comment]
@173210 Please help us :(

**Comment by PHF42** [comment]
I believe this is related to #263: the Git history has been rewritten from 0f112a6 to 9711d25 in order to remove any trace of `rxtools/source/features/TitleKeyDecrypt.*`.
This has correctly created an alternate Git history, spanning from 3b7e041 to 014f017. However, instead of becoming the new master branch, it has been merged with the old Git history by 8b03aca.

To fix the issue, I would suggest:
1. Create a temporary backup branch on origin/master.
2. Reset the master branch to 014f017.
3. Re-add `TitleKeyDecrypt.h` as in 8b03aca.
4. Cherry-pick all commits that occurred to origin/master _after_ 8b03aca.
5. Perform a forced update of the master branch.
6. If everything is OK, remove the backup branch created at step 1. This will actually fix #263.

Warning: the forced update at step 4 may require [an extra work for all clones with WIP](http://stackoverflow.com/q/9813816). This is however the only way to solve #263.

**Comment by 173210** [comment]
Well, Git is not good at history repairing and it has only minimal features for that.

**Comment by 173210** [comment]
Ok, I made a fixed branch in my repository. Check out this and push -f.
https://github.com/173210/rxTools/tree/work
```
git pull https://github.com/173210/rxTools.git work:work
git branch -D master
git branch -m work master
git push -f origin master:master
```

**Comment by AlbertoSONIC** [comment]
@173210 Ok I'll do it once I get home ;)

**Comment by 173210** [comment]
Why is this still unsolved?

**Comment by AlbertoSONIC** [comment]
Fixed!
