### ISSUE TITLE
Nand dumper is broken

### ISSUE THREAD

**Issue by AlbertoSONIC** [roxas75/rxTools#282]
There are many reports fron users that the dump obtained with rxTools' nand dumper is broken and flashing it to the nand would translate in a brick

**Comment by Syphurith** [comment]
Orz. @AlbertoSONIC Then what if they use the decrypt9 for the nand?

**Comment by AlbertoSONIC** [comment]
@Syphurith I don't know if it's working on decrypt9, I guess it is

**Comment by 173210** [comment]
Maybe fixed with commit 5c9d55434060da4fb639b3628d8147351da43e69 and e47b503673072467a7ac57f198d45db1a05516ad in #280.
By the way, isn't this duplicated of #274 and #276?

**Comment by AlbertoSONIC** [comment]
@173210 Nope, here we talk about the fact that the nand dumper outputs a broken NAND.bin

**Comment by xadox-1st** [comment]
Is NAND dump working again?

**Comment by capito27** [comment]
Ok, i just dumped my Nand with the latest Nightly including 173210's fixes, and flashed it back to my emunand, it booted fine. Can someone with a Nand mod test it on O3DS or N3DS ?

**Comment by 173210** [comment]
I had a dump smaller than ones dumped with a MMC reader (hardware mod). Is it correct?

**Comment by capito27** [comment]
@173210, yes, it is supposed to be a bit smaller than hardmod one or
gateway, Could you please write the nand backup from rxTools to nand (using
the hardmod or gateway) and test to see if it boots fine (shouldn't have to
say this, but make sure to have another backup from somewhere else first)

**Comment by urherenow** [comment]
I just made a dump on my N3DS with rxtools, and with hard mod. It produced exactly the same size dump. Hash differences are expected because of the date/time and the system is obviously running when using rxtools (same as hard mod or using any other tool, take a backup, turn the system on and off again without doing anything else, and take another backup; the hash will be different.

Flashed the rxtools dump and sysnand works fine (as does TWL, AGB, and the menuhax I had installed).This issue appears to be corrected and can be closed.

**Comment by capito27** [comment]
As per this post on gbatemp (
https://gbatemp.net/threads/release-rxtools-roxas75-3ds-toolkit-fw-2-0-9-2.382782/page-723#post-5808978
)
, i assume that the nand dumper is now fixed since it has been reported to
work fine in both N3DS (by myself) and O3DS.

This issue can be closed for now.
