### ISSUE TITLE
2DS - Viewing "Ver." at the place of "RX-E" on emuNAND after loading BigBleuMenu

### ISSUE THREAD

**Issue by mariogamer2** [roxas75/rxTools#319]
2DS 6.0.0-12U with MSET exploit
emuNAND 10.3 unlinked

When loading BBM,the notice of firmware is "RX-E",but,when leaving it and boot system setting,the firmware is: "Ver. 10.3.0-28U",and this is not my sysNAND,because,when leaving setting,it load the old home menu.

I'll post a video soon.

**Comment by AlbertoSONIC** [comment]
That's because we stop seatching and patching the Ver. string once it has been found. When you open settings, the arm9 thread finds the Ver. string and replaces it... If you open BBM first, it founds the Ver. string inside it and stops searching for Ver... The only solution would be keep scanning for Ver. string even if it has been found. What do you think @nastys @capito27 @motezazer @lavanoid @173210 ?

**Comment by motezazer** [comment]
I think it would be a good idea to keep scanning, because there is no reason to not.

**Comment by AlbertoSONIC** [comment]
Well then, if you can commit that change do it as I'm not at home till 30th ;)

**Comment by motezazer** [comment]
I will be able to do it the 27th.

**Comment by AlbertoSONIC** [comment]
Then do it the 27th (if no one does it before) :)

**Comment by lavanoid** [comment]
I too would vote for constant scanning of the ver string. If I was to attempt to commit a change, I'd likely blow up rxTools along with it :P 

(My C is so bad)

**Comment by mariogamer2** [comment]
Ok,thank guys.
