### ISSUE TITLE
Gitter chat

### ISSUE THREAD

**Issue by roxas75** [roxas75/rxTools#43]
What about a Gitter open chat?

**Comment by idgrepthat** [comment]
People will beg for irc instead even though you already have that. People cling to traditions.

Just go ahead and open gitter and people will use it if they feel like it - there's no disadvantage to using the free service. I think it's a good idea since posts are logged and not lost forever like irc.

**Comment by roxas75** [comment]
Well, if it will be filled with shitty messages i'll close it.
Yeah, it's a better way to comunicate when the others are online.
I'll open it right now.
