### ISSUE TITLE
[Enhancement] Allow games to use Full Clock Speed & Ram on N3DS

### ISSUE THREAD

**Issue by RinMaru** [roxas75/rxTools#456]
So I heard NTR allows games to use the N3DS clock speed to make old unsupported games load faster and lag less could this be implemented into rxNand

**Comment by Hartie95** [comment]
NTR doesn't do anything to ram, but you could set the clockspeed with the plugin.
Aureinand on the other side allows homebrew, and possible future games to use more ram, using a new reboot patch, which doesn't block TWL and AGB firm booting.

**Comment by RinMaru** [comment]
Could this be added as a default or it could be set in options to turn on when rxNand launches?

**Comment by Hartie95** [comment]
This value will be changed every time an application is launched, so you would need to patch the module which sets it, to always use the highest clock.

**Comment by RinMaru** [comment]
Im no programer but im gathering this wont happen anytime soon but it is possible and would require allot of coding. I know HANS does this and @ApacheThunder  is making patches for random games.

**Comment by urherenow** [comment]
HANS is open source, so it's really a matter of someone feeling like doing it. Seeing as rxCFW doesn't do anything at all for TWL on N3DS, I'd say the devs are more worried about that.

**Comment by RinMaru** [comment]
I dont see why nintendo can't make this a feature themselves

**Comment by Hartie95** [comment]
From what I know there a some games having trouble to run properly, if you change the clock speed.

**Comment by RinMaru** [comment]
Apparently its a HANS issue Apache Thunder has confirmed this I believe with LOZOOT he got stuttering in HANS but got no issues with his custom patches

**Comment by Shadow322** [comment]
What about with NTR?

**Comment by sykhro** [comment]
This shouldn't be implemented for a couple reasons:
- Some games get glitched 
- The audio gets bugged depending on the type of audio api used
- Using more resources makes the battery run low quicker 
- You end up with just slightly better loading times. The only game that really gets better with this is MH3U.

**Comment by RinMaru** [comment]
@sykhro it could be optional It reduces lag a bit in Pokemon XY also

**Comment by sykhro** [comment]
Just use a modified ExHeader, that way you can set different hardware options for specific games. Keeping everything locked to the maximum doesn't seem very clean to me

**Comment by RinMaru** [comment]
I have no idea how to do that >"<

**Comment by ApacheThunder** [comment]
Yes many games could see an improvement. But this won't always be the case. Although the audio bugs with Ocarina of Time do not occur via my patches like they do with Hans. I have not tested NTR, because NTR is not compatible with the FIRM I'm currently running.

Even so, it's probably not a good idea to try and enable this globally. In perticular, older homebrew may not get along with this and it could still break things with retail games. I have not found any games (yet) that break as a result of my patches, but if one does crop up, it will end up broken the same way if this was enabled globally. (note that my Pokemon patches also enable the extra ram unlike most of my other patches)

I concur with sykhro on this. Just use a patch to do it for the specific games you want. If you run into a game that doesn't like it. Uninstall the patch. That would be easier to do then dealing with a CFW that forces it on for everything. :P

My patches are probably the best route for CFW users. NTR and hans does it just fine, but there's no gurantee they'll work with future firmware updates (as is the case with NTR. It still won't work if running latest native_firm). So my patches were the solution to that.

Having CFW doing it is probably unnessecery. If you want to create a patch yourself, it's not too difficult. (even easier if the game you will modify already had a official patch. Then you can modify that instead)

You simply change offsets 0x20C and 0x60C to 02 or 03 in the exheader (03 enables the extra ram. 02 just enables the extra CPU speed) (these two offsets should always match each other, otherwise the exheader will be determined as invalid and the patch/game won't work)

If the game did not have an official patch, it gets a little more complicated. You will need to also change offset 0x11C to 0E to change it's content type to patch. (also don't include romfs in this patch because .code won't be configured correctly to use it, so you're just wasting space Only official patches will make use of romfs correctly).

Then once the CXI is built (assuming you used 3dstool to rebuild the CXI) you modify offsets 0x10C and 1CC to be 0E. This changes the CXI to a patch. Failing to do this will cause the resulting CIA to attempt to install as an application (aka full game), which could replace your game and just break things. :P

Note that conversions of cartridge based games requires an extra change to the exheader. Since they have the "run from SD" flag disabled in the exheader. You need to change offset 0x0D to 03. This enables SD and "compressed code".

If for some odd reason the game in question doesn't use compressed code (I did come across a couple that didn't. Animal Crossing New Leaf for example). Then just compress the .code and rebuild the exefs. I don't know the bit settings for that offset offhand that would have SD enabled but compression disabled. I just compressed code to get around that issue. :P

**Comment by RinMaru** [comment]
Thanks for the info @ApacheThunder Ill close this then
